model {
  file: "model.sdf"
  file_format {
    version {
      major: 1
      minor: 6
    }
    name: "sdf"
  }
}
name: "dust_emitter_dense"
description: "A dense dust generator."
authors {
  name: "Carlos Aguero"
  email: "caguero@openrobotics.org"
}

